### ISSUE TITLE
[Error]运行错误

### ISSUE THREAD

**Issue by kmq132** [littleseven2003/FaceRecognitionSystem#15]
运行时给出报错
```
读取配置文件出错: 'gbk' codec can't decode byte 0xa8 in position 17: illegal multibyte sequence
Traceback (most recent call last):
  File "d:\RaspberryPi\FaceRecognitionSystem\Core.py", line 446, in <module>
    data_manager = DataManager.DataManager()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\RaspberryPi\FaceRecognitionSystem\DataManager.py", line 15, in __init__
    self.read_config()
  File "d:\RaspberryPi\FaceRecognitionSystem\DataManager.py", line 24, in read_config
    config.read('.config')
  File "D:\anaconda3\envs\RaspBerryPi\Lib\configparser.py", line 713, in read
    self._read(fp, filename)
  File "D:\anaconda3\envs\RaspBerryPi\Lib\configparser.py", line 1037, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 17: illegal multibyte sequence
```

**Comment by littleseven2003** [comment]
## 问题原因：
这个错误提示说明在读取配置文件时，Python试图使用GBK编码解析文件内容，但遇到了非法的多字节序列。一般来说，这个问题可以通过确保使用正确的文件编码来解决。
## 解决方式：
修改DataManager.py中读取.config文件方式为如下：
```
# 使用 open 方法指定编码
            with open('.config', 'r', encoding='utf-8') as configfile:
                config.read_file(configfile)
```

**Comment by littleseven2003** [comment]
已经提交到debug-code-standard分支，请查看是否解决问题
